### PR TITLE
fix: unsupported attribute when using policy_bindings

### PR DESCRIPTION
**Pull request by czerasz-mineiros**
When using `policy_bindings` the following issue occurs:

```
Error: Unsupported attribute

  on .terraform/modules/secret/iam.tf line 21, in module "iam":
  21:   members         = each.value.members
    |----------------
    | each.value is object with 1 attribute "policy_bindings"

This object does not have an attribute named "members".
```

### CODE REVIEW

**Review by kwilczynski — APPROVED** [review]
Thank you for fixing this!

**Review by kassianh — APPROVED** [review]
lgtm

**Review by soerenmartius — CHANGES_REQUESTED** [review]
lgtm!

@czerasz please add the changes to the CHANGELOG.md also and prepare a new minor version to be released, thanks! (that's why I am requesting changes)

**Comment by czerasz-mineiros** [comment]
@soerenmartius updated the `CHANGELOG.md` but changed the patch version since this is only a fix. Hope this fine

**Review by soerenmartius — APPROVED** [review]
lgtm! thanks!

**Pull request merged**
